### ISSUE TITLE
Question about how this spawns a server.

### ISSUE THREAD

**Issue by SamuelGogarty** [glenndehaan/csgo-matchmaking#15]
Hi, came across this project while looking into an idea of a project I have.

A simple matchmaking service for CS 1.6.

I am wondering where in your project are CSGO specifics, so I could attempt it modify it to meet HLDS requirements.
Does this project deploy a container when a match is organized?

anyway, impressive project, cheers!

**Comment by SamuelGogarty** [comment]
after digging around more, it seems there is no orchestration in this, but rather has a definition of servers, it seems like no modification is needed in this regard, as it will try to match with whatever is listening on the defined hosts, on the specified ports, so it seems so far at least.

**Comment by glenndehaan** [comment]
Hi, Yeah you are correct. Within this prototype you define your servers within the config file and are then given out to players.

**Comment by SamuelGogarty** [comment]
I think some sort of container automation would be a really cool thing to implement, but im not exactly experienced with any of the tools you implemented, if I do figure out a way i'll be sure to send it back your way, thanks for getting back to me.
